### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by JoelSParker** [flurrybox/enhanced-privacy-m1#1]
Are you able to outline the functionality this offers?

**Comment by flurrybox** [comment]
Hey,

Purpose of extension is to help Magento 1 store owners comply with GDPR much easier.

- Customers can export their data in .zip archive containing .csv files with personal, wishlist, quote, and address data (its possible to implement your own data entities for customers to export).
- Customer can delete or anonymize their account. Current password and reason is required. Account will be deleted within 1 hour (or as specified in configuration), in this time span its possible for customers to undo deletion.
- If customer has made at least one order, they are ineligible to delete their account, instead it will be anonymized.
- When a customer visits your store for the first time, a popup notification about cookie policy will be shown.
