### ISSUE TITLE
How to install the extension?

### ISSUE THREAD

**Issue by ghost** [flurrybox/enhanced-privacy-m1#3]
Hi,

I tried to download the zip from GitHub, then I went to Magento Connect Manager -> Upload package file. After clicking "Upload" with the zip selected Magento shows:
```
CONNECT ERROR: Package file is invalid
Invalid package name, allowed: [a-zA-Z0-9_-] chars
Invalid version, should be like: x.x.x
Invalid stability
Invalid date, should be YYYY-DD-MM
Invalid channel URL
Empty authors section
Empty package contents section
```
Can you help?

**Comment by henkvalk** [comment]
https://github.com/henkvalk/enhanced-privacy-m1

**Comment by henkvalk** [comment]
Please upload through FTP in your Magento root folder

**Comment by ghost** [comment]
I tried that too but it gives:
```
[22-May-2018 21:47:33 UTC] PHP Parse error:  syntax error, unexpected '[' in ████/app/code/community/Flurrybox/EnhancedPrivacy/sql/flurrybox_enhancedprivacy_setup/install-0.0.1.php on line 26
```
and there is no easy way to remove the copied files.

**Comment by ghost** [comment]
@flurrybox Why did you close this without even replying?

**Comment by flurrybox** [comment]
### Installation
> Download files
Upload the files to your Magento Root
Flush Cache
Logout and Login into Magento
Go to System > Configuration > Customer > Customer Options > Privacy (GDPR)
Enable and configure extension as necessary

As for your error, which PHP version are you running Magento on?

**Comment by ghost** [comment]
I have followed the steps (cache and compilation are completely disabled) yet I am still getting the error. PHP version is 5.3.24

**Comment by henkvalk** [comment]
Php5.4 is minimum requirements. See also the readme. Also for security ita better to update to min. php 5.6

**Comment by ghost** [comment]
I see now in the prerequisites were updated after opening this issue:

https://github.com/flurrybox/enhanced-privacy-m1/commit/8cab79a1a7de7fd33714eff3c417545cfd14d989

May I please ask how to install on Magento 1.9.1.0 and the specified PHP version?

**Comment by henkvalk** [comment]
First you need to update your php version.

**Comment by flurrybox** [comment]
Hey @anchev, did you manage to resolve your issue?

**Comment by ghost** [comment]
@flurrybox The actual issue currently is: info about version requirement added after my question, i.e. not really my issue. tried switching to PHP7 but that breaks my Magento installation, so I had to switch back to 5.3.24. Unfortunately I have no ability or time to experiment with other versions. While I understand you may not be willing to provide support for versions not meeting these requirements, I would hope for that.

**Comment by henkvalk** [comment]
Maybe you can try the Inchoo extension for the PHP7
[https://github.com/Inchoo/Inchoo_PHP7](https://github.com/Inchoo/Inchoo_PHP7)

**Comment by ghost** [comment]
Perhaps it would make more sense to find out a way to migrate to Magento 2... I am searching for info.

**Comment by flurrybox** [comment]
Closing as op has deleted his account
