### ISSUE TITLE
What condition is required to make the account will be deleted within specified time ?

### ISSUE THREAD

**Issue by Cybercladou** [flurrybox/enhanced-privacy-m1#6]
Hi Flurrybox Team,

Thanks for the great extension.

I tried the account deleted feature but it seems the account still there after 1 hour or anytime I set in configuration. I'm running XAMPP in pc for developing and testing, so don't know any conditions (or　server configuration) is required to trigger the delete action ?

**Comment by gino2014** [comment]
Hi Cybercladou,
the deletion is set at the configuration page with minutes. It works fine, but you need to running cron job for the deletion of a customer account.
Regards Gino

**Comment by Cybercladou** [comment]
Thanks Gino,
Just want to clarify, the Cron job you're mention is the server OS platform cron job ? (if yes, is it any script in the package I can reference ?)Or actually you're mention the cron jon in magento (System > Configuration > Advanced > system > Cron tab) ?
p.s. FYR, I'm running Magento CE 1.7.

Thanks a lot !

Best Regards,
Doug. 

    On Thursday, May 31, 2018, 6:20:10 PM GMT+8, gino2014 <notifications@github.com> wrote:  
 
 
Hi Cybercladou,
the deletion is set at the configuration page with minutes. It works fine, but you need to running cron job for the deletion of a customer account.
Regards Gino

**Comment by Cybercladou** [comment]
Hi Gino,
I take a look of the config.xml, I figure it out you're talking about the magento cron job. I think it is because I'm running magento in Xampp for windows, so the cron job didn't work. I'll try to test it on linux system and see if any problem, thanks a lot !

Best Regards,
Doug. 

    On Thursday, May 31, 2018, 6:20:10 PM GMT+8, gino2014 <notifications@github.com> wrote:  
 
 
Hi Cybercladou,
the deletion is set at the configuration page with minutes. It works fine, but you need to running cron job for the deletion of a customer account.
Regards Gino

**Comment by gino2014** [comment]
Hi Cybercladou,
you are right i talked about cron job that runs at a server. Additional infos for magento 1 you get it here:
https://docs.magento.com/m1/ce/user_guide/system-operations/cron.html

**Comment by flurrybox** [comment]
Hey @Cybercladou is there still an issue?

**Comment by Cybercladou** [comment]
Sorry for the late reply, I found the email stuck in my outbox today...

I still not yet put it on Linux environment to test because waiting for the client confirmation.
Just in case I didn’t missed anything, let me confirm one more thing : the cron job in flurrybox should be no need to setup separately if magento system already have a cron.php running normally, right ? (cron.php is setup to be run by schedule)

Thanks a lot !

**Comment by flurrybox** [comment]
Hey,
Its enough with Magento cron.php, no need to setup anything separately.
